
services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: shoppingdb
      MYSQL_USER: shop
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend-api:
    image: onkarlonkar9/backend-api:v1
    container_name: backend-api
    restart: always
    depends_on:
      - mysql-db
    environment:
      PORT: 8000
      DB_HOST: mysql-db
      DB_USERNAME: shop
      DB_PASSWORD: pass123
      DB_NAME: shoppingdb
    ports:
      - "8000:8000"

  vendor-ui:
    image: onkarlonkar9/frontend-vendor:v2
    container_name: vendor-ui
    restart: always
    ports:
      - "5173:80"
    volumes:
      - ./vendor-nginx.conf:/etc/nginx/conf.d/default.conf

  customer-ui:
    image: onkarlonkar9/frontend-customer:v2
    container_name: customer-ui
    restart: always
    ports:
      - "5174:80"
    volumes:
      - ./customer-nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql-data:

